config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do

     resources  :posts, except: [:index]
  resources :advertisements
end
resources  :users, only: [:new, :create, :show]

resources :posts, only: [] do
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
end
resources :questions

    resources :sessions, only: [:new, :create, :destroy]


        post   "/confirm" => "users#confirm"


  get 'about' => 'welcome#about'
  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
      resources :posts, only: :create
    end
    resources :posts, only: [:index, :show, :update, :destroy]
      resources :comments, only: [:index, :show]
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  def index
    @question = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params.require(:question).permit(:title, :body, :resolved))

    if @question.save
      flash[:notice] = "Question was saved."
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question. Please try again."
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params.require(:question).permit(:title, :body, :resolved))
      flash[:notice] = "Question was updated."
      redirect_to @question
    else
      flash[:error] = "There was an error saving the questions. Please try again."
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:notice] = "Question has been deleted."
      redirect_to @question
    else
      flash[:error] = "There was an error deleting the question. Please try again"
    render :edit
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      redirect_to @question, notice: "Question was saved successfully."
    else
      flash[:error] = "Error creating Question. Please try again."
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      flash[:notice] = "Question was updated."
      redirect_to @question
    else
      flash[:error] = "Error saving question. Please try again."
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "\"#{@question.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the question."
      render :show
    end
  end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guideline for question</p>
    <ul>
      <li>Make sure that it rhymes.</li>
      <li>Don't use the letter "A"</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter question title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter question title" %>
      </div>
      <div class="form-group">
        <%= f.label :"Resolved?" %>
        <%= f.check_box :resolved %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/questions/index.html.erb
<h1>Questions</h1>

<div class="row">
  <div class="col-md-8">

    <% @questions.each do |question| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">

          <%= link_to question.title, question %>
        </h4>
        <small>
          <%= question.body %>
          </small>
      </div>
    </div>
  <div class="col-md-4">
    <%=  "solved" if question.resolved %>
    <%=  "open" if !question.resolved %>
    <%= link_to "New Question", new_question_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for questions:</p>
    <ul>
      <li>Make sure the question is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%=f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter question " %>
      </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :title, rows: 8, class: 'form-control', placeholder: "Enter question description" %>
        </div>
        <div class="form-group">
          <%= f.label :"Resolved?" %>
          <%= f.check_box :resolved %>
        </div>
        <%= f.submit "Save", class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

 <%= link_to "Edit Question", edit_question_path, class: 'btn btn-success' %>
 <%= link_to "Delete Question", @question, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this question?' } %>